stages:
  - test

default:
  image: python:3.12
  before_script:
    - python -m venv env
    - source env/bin/activate
    - wget https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/12.2.0/ubuntu_24.10_graphviz-12.2.0-cmake.deb
    - dpkg --install ubuntu_24.10_graphviz-12.2.0-cmake.deb
    - pip install .

test-django-execution:
  stage: test
  tags:
    - bacardi2
    - docker
  script:
    - cd example/
    - python -m django --version
    - python manage.py test tests
