# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
# SPDX-FileContributor: Benjamin Moritz Bauer <benjamin.bauer@dlr.de>
#
# SPDX-License-Identifier: MIT

variables:
  ARTIFACTORY_AUTH: $ARTIFACTORY_USER:$ARTIFACTORY_TOKEN
  PYPI_MIRROR: https://$ARTIFACTORY_AUTH@$PYPI_DOMAIN/$PYPI_REMOTE/simple

stages:
  - test
  - audit
  - docs
  - package
  - publish

default:
  tags:
    - sc
    - docker
  image: $DOCKERHUB_MIRROR/python:3.12
  before_script:
    - mkdir -p build
    - apt update -y
    - apt install -y graphviz graphviz-dev
    - pip install -e ".[test, develop]"

.default_publish_rules:
  rules:
    # Publish only from tag pipelines with matching tag pattern
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/

test-django-execution:
  stage: test
  tags:
    - sc
    - docker
  script:
    - cd example/
    - python -m django --version

coverage-report:
  stage: test
  script:
    - pytest --cov --cov-report=term --cov-report=html --cov-report=xml --junitxml=build/test-report.xml tests/
  artifacts:
    expose_as: "Coverage Report"
    paths:
      - build/html-coverage/
    reports:
        junit: build/test-report.xml
        coverage_report:
          coverage_format: cobertura
          path: build/coverage.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

validate_release_tag:
  stage: test
  script:
    - python -c "import django_prov; assert django_prov.__version__ == '$CI_COMMIT_TAG'"
  rules:
    - !reference [.default_publish_rules, rules]

license-check:
  stage: audit
  tags:
    - sc
    - docker
  script:
    - reuse lint -j >> build/license_report.json
  artifacts:
    expose_as: "License Report"
    paths:
      - build/license_report.json

citation-check:
  stage: audit
  tags:
    - sc
    - docker
  script:
    - cffconvert --validate
  artifacts:
    expose_as: "License Report"
    paths:
      - build/license_report.json

build-docs:
  stage: docs
  script:
    - sphinx-build -t sphinx -b html docs/ build/docs/
  artifacts:
    paths:
      - build/docs/

pages:
  stage: publish
  script:
    - mkdir public
    - cp -r build/docs/* public/.
  artifacts:
    paths:
      - public
  rules:
    - !reference [.default_publish_rules, rules]

package:
  stage: package
  script:
    - pip wheel -w dist .
  artifacts:
    paths:
      - dist

publish-to-gitlab:
  stage: publish
  variables:
    PYPI_GITLAB: https://gitlab-ci-token:$CI_JOB_TOKEN@$GITLAB_DOMAIN/api/v4/projects/58836/packages/pypi
  script:
    - pip install twine
    - twine upload --repository-url $PYPI_GITLAB --verbose dist/django_prov*.whl
  rules:
    - !reference [.default_publish_rules, rules]

publish-to-artifactory:
  stage: publish
  variables:
    PYPI_INTERNAL: https://$ARTIFACTORY_AUTH@$PYPI_DOMAIN/$PYPI_LOCAL
  script:
    - pip install twine
    - twine upload --repository-url $PYPI_INTERNAL --verbose dist/django_prov*.whl
  rules:
    - !reference [.default_publish_rules, rules]
