stages:
  - test
  - publish

default:
  image: python:3.12
  before_script:
    - apt update -y
    - apt install -y graphviz graphviz-dev
    - python -m venv env
    - source env/bin/activate
    - pip install ".[test]"

test-django-execution:
  stage: test
  tags:
    - bacardi2
    - docker
  script:
    - cd example/
    - python -m django --version
    - python manage.py test tests

coverage-report:
  stage: test
  tags:
    - bacardi2
    - docker
  script:
    - coverage run --source="django_prov" example/manage.py test
    - coverage html
  artifacts:
    expose_as: "Coverage Report"
    paths:
      - htmlcov/

publishing-process:
  stage: publish
  variables:
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_USERNAME: gitlab-ci-token
  tags:
    - bacardi2
    - docker
  script:
    - pwd
    - ls -la
    - pip install twine
    - pip install -e .
    - pip wheel -e .
    - twine upload --repository-url https://gitlab.dlr.de/api/v4/projects/11169/packages/pypi --verbose django_prov*.whl
  when: manual
