[build-system]
requires = ['setuptools']
build-backend = "setuptools.build_meta"

[project]
name = "django-prov"
description = "Application for capturing Provenance Data in Django projects "
authors = [
    {name = "Benjamin Bauer", email = "benjamin.bauer@dlr.de"},
]
requires-python = ">=3.8"
license = {text = "License :: Other/Proprietary License"}
dependencies = [
    "Django",
    "prov[dot]==2.0.1",
]
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]
dynamic = ["version", "readme"]

[project.urls]
"Code" = "https://gitlab.dlr.de/ssa/django-prov"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-django",
    "pytest-cov",
    "hypothesis"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.dynamic]
version = {attr = "django_prov.__version__"}
readme = {file = ["README.rst"]}

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "example.settings"

[tool.coverage.run]
branch = true
data_file = "build/coverage"
source_pkgs = ["django_prov"]

[tool.coverage.report]
include = [
    "*/django_prov/*"
]
omit = [
    "*__init__.py"
    ]

[tool.coverage.html]
directory = "build/html-coverage"
title = "Pytest Coverage Report"

[tool.coverage.xml]
output = "build/coverage.xml"
