# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
# SPDX-FileContributor: Benjamin Moritz Bauer <benjamin.bauer@dlr.de>
#
# SPDX-License-Identifier: MIT

"""
This file holds different regex patterns to validate the output of the ProvenanceGenerator during integration tests.
"""

order_create_pattern = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django\_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-2-.*, .*\)\n',
    r'  entity\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasAttributedTo\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Borrowing_ordered_books-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Borrowing_borrowed_books-2-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-2-.*, django:foo22-.*, -\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-2-.*, example:Book-1-.*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-2-.*, example:Book-2-.*\)\n',
    r'  activity\(django:foo22-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(django:foo22-.*, auth:User-1-.*, -\)\n',
    r'endDocument',
]

order_create_pattern_no_borrowing = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django\_prov/>\n',
    r'  \n',
    r'  activity\(django:foo22-.*, .*, .*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasAssociatedWith\(django:foo22-.*, auth:User-1-.*, -\)\n',
    r'endDocument',
]

order_create_pattern_no_auth_no_borrowing = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django\_prov/>\n',
    r'  \n',
    r'  activity\(django:foo22-.*, .*, .*, .*\)\n',
    r'endDocument',
]

order_create_pattern_no_book = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django\_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-2-.*, .*\)\n',
    r'  entity\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasAttributedTo\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Borrowing_ordered_books-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Borrowing_borrowed_books-2-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-2-.*, django:foo22-.*, -\)\n',
    r'  activity\(django:foo22-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(django:foo22-.*, auth:User-1-.*, -\)\n',
    r'endDocument',
]

order_create_pattern_no_student_no_librarian = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django\_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-2-.*, .*\)\n',
    r'  entity\(example:Borrowing_ordered_books-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Borrowing_ordered_books-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Borrowing_borrowed_books-2-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-2-.*, django:foo22-.*, -\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-2-.*, example:Book-1-.*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-2-.*, example:Book-2-.*\)\n',
    r'  activity\(django:foo22-.*, .*, .*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasAssociatedWith\(django:foo22-.*, auth:User-1-.*, -\)\n',
    r'endDocument',
]

order_create_pattern_student_and_librarian_agent = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django\_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-2-.*, .*\)\n',
    r'  agent\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasInfluencedBy\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  wasAttributedTo\(example:Borrowing-2-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Borrowing_ordered_books-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-2-.*, example:Borrowing_borrowed_books-2-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-2-.*, django:foo22-.*, -\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-2-.*, example:Book-1-.*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-2-.*, example:Book-2-.*\)\n',
    r'  activity\(django:foo22-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(django:foo22-.*, auth:User-1-.*, -\)\n',
    r'endDocument',
]


borrowing_start_pattern = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  entity\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasAttributedTo\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Borrowing-1-.*, example:Borrowing-1-.*, -, -, -\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Librarian-1-.*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasAttributedTo\(example:Librarian-1-.*, auth:User-2-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-1-.*, django:foo23-.*, -\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, django:foo23-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, django:foo23-.*, -\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  activity\(django:foo23-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(django:foo23-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]

borrowing_start_pattern_no_borrowing = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django\_prov/>\n',
    r'  \n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, django:foo23-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, django:foo23-.*, -\)\n',
    r'  activity\(django:foo23-.*, .*, .*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasAssociatedWith\(django:foo23-.*, auth:User-2-.*, -\)\n',
    r'endDocument',
]

borrowing_start_pattern_no_auth_no_borrowing = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django\_prov/>\n',
    r'  \n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, django:foo23-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, django:foo23-.*, -\)\n',
    r'  activity\(django:foo23-.*, .*, .*, .*\)\n',
    r'endDocument',
]

borrowing_start_pattern_no_book = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  entity\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasAttributedTo\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Borrowing-1-.*, example:Borrowing-1-.*, -, -, -\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Librarian-1-.*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasAttributedTo\(example:Librarian-1-.*, auth:User-2-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-1-.*, django:foo23-.*, -\)\n',
    r'  activity\(django:foo23-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(django:foo23-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]

borrowing_start_pattern_no_student_no_librarian = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Borrowing-1-.*, example:Borrowing-1-.*, -, -, -\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-1-.*, django:foo23-.*, -\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, django:foo23-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, django:foo23-.*, -\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  activity\(django:foo23-.*, .*, .*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasAssociatedWith\(django:foo23-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]

borrowing_start_pattern_student_and_librarian_agent = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  agent\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasInfluencedBy\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  wasAttributedTo\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Borrowing-1-.*, example:Borrowing-1-.*, -, -, -\)\n',
    r'  wasAttributedTo\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  agent\(example:Librarian-1-.*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasInfluencedBy\(example:Librarian-1-.*, auth:User-2-.*\)\n',
    r'  wasAttributedTo\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-1-.*, django:foo23-.*, -\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, django:foo23-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, django:foo23-.*, -\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  activity\(django:foo23-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(django:foo23-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]


borrowing_return_pattern = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, example:foo2-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, example:foo2-.*, -\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  entity\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasAttributedTo\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Librarian-1-.*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasAttributedTo\(example:Librarian-1-.*, auth:User-2-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Borrowing-1-.*, example:Borrowing-1-.*, -, -, -\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-1-.*, example:foo2-.*, -\)\n',
    r'  activity\(example:foo2-.*, .*, .*, .*\)\n',
    r'  wasInformedBy\(example:foo2-.*, example:foo-.*\)\n',
    r'  activity\(example:foo-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(example:foo-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]

borrowing_return_pattern_no_borrowing = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, example:foo2-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, example:foo2-.*, -\)\n',
    r'  activity\(example:foo2-.*, .*, .*, .*\)\n',
    r'  wasInformedBy\(example:foo2-.*, example:foo-.*\)\n',
    r'  activity\(example:foo-.*, .*, .*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasAssociatedWith\(example:foo-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]

borrowing_return_pattern_no_auth_no_borrowing = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, example:foo2-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, example:foo2-.*, -\)\n',
    r'  activity\(example:foo2-.*, .*, .*, .*\)\n',
    r'  wasInformedBy\(example:foo2-.*, example:foo-.*\)\n',
    r'  activity\(example:foo-.*, .*, .*, .*\)\n',
    r'endDocument'
]

borrowing_return_pattern_no_book = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  entity\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasAttributedTo\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  entity\(example:Librarian-1-.*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasAttributedTo\(example:Librarian-1-.*, auth:User-2-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Borrowing-1-.*, example:Borrowing-1-.*, -, -, -\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-1-.*, example:foo2-.*, -\)\n',
    r'  activity\(example:foo2-.*, .*, .*, .*\)\n',
    r'  wasInformedBy\(example:foo2-.*, example:foo-.*\)\n',
    r'  activity\(example:foo-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(example:foo-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]

borrowing_return_pattern_no_student_no_librarian = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, example:foo2-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, example:foo2-.*, -\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Borrowing-1-.*, example:Borrowing-1-.*, -, -, -\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-1-.*, example:foo2-.*, -\)\n',
    r'  activity\(example:foo2-.*, .*, .*, .*\)\n',
    r'  wasInformedBy\(example:foo2-.*, example:foo-.*\)\n',
    r'  activity\(example:foo-.*, .*, .*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasAssociatedWith\(example:foo-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]

borrowing_return_pattern_student_and_librarian_agent = [
    r'document\n',
    r'  default <example\.org/>\n',
    r'  prefix auth <example\.org/auth/>\n',
    r'  prefix django <example\.org/django/>\n',
    r'  prefix sys <example\.org/sys/>\n',
    r'  prefix example <example\.org/example/>\n',
    r'  prefix django_prov <example\.org/django_prov/>\n',
    r'  \n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  entity\(example:Book-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-1-.*, example:Book-1-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-1-.*, example:foo2-.*, -\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  entity\(example:Book-2-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Book-2-.*, example:Book-2-.*, -, -, -\)\n',
    r'  wasGeneratedBy\(example:Book-2-.*, example:foo2-.*, -\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  agent\(example:Student-1-.*, .*\)\n',
    r'  agent\(auth:User-1-.*, .*\)\n',
    r'  wasInfluencedBy\(example:Student-1-.*, auth:User-1-.*\)\n',
    r'  wasAttributedTo\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  agent\(example:Librarian-1-.*, .*\)\n',
    r'  agent\(auth:User-2-.*, .*\)\n',
    r'  wasInfluencedBy\(example:Librarian-1-.*, auth:User-2-.*\)\n',
    r'  wasAttributedTo\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing-1-.*, .*\)\n',
    r'  wasDerivedFrom\(example:Borrowing-1-.*, example:Borrowing-1-.*, -, -, -\)\n',
    r'  wasAttributedTo\(example:Borrowing-1-.*, example:Student-1-.*\)\n',
    r'  wasAttributedTo\(example:Borrowing-1-.*, example:Librarian-1-.*\)\n',
    r'  entity\(example:Borrowing_ordered_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_ordered_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_ordered_books-1-.*, example:Book-2-.*\)\n',
    r'  entity\(example:Borrowing_borrowed_books-1-.*, .*\)\n',
    r'  hadMember\(example:Borrowing-1-.*, example:Borrowing_borrowed_books-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-1-.*\)\n',
    r'  hadMember\(example:Borrowing_borrowed_books-1-.*, example:Book-2-.*\)\n',
    r'  wasGeneratedBy\(example:Borrowing-1-.*, example:foo2-.*, -\)\n',
    r'  activity\(example:foo2-.*, .*, .*, .*\)\n',
    r'  wasInformedBy\(example:foo2-.*, example:foo-.*\)\n',
    r'  activity\(example:foo-.*, .*, .*, .*\)\n',
    r'  wasAssociatedWith\(example:foo-.*, auth:User-2-.*, -\)\n',
    r'endDocument'
]
